/**
 * AI Automation Agent (planning layer)
 *
 * Purpose:
 * - Interpret a user goal and break it into an actionable multi-step automation plan.
 * - This is intentionally deterministic + heuristic today.
 * - Later: replace internals with an LLM call (Claude) and validate the response.
 */

export type AutomationPlan = {
  workflow_name: string;
  tasks: string[];
  suggested_integrations: string[];
};

function uniq(items: string[]) {
  return Array.from(new Set(items));
}

/**
 * Plan an automation from a natural language prompt.
 */
export async function planAutomation(prompt: string): Promise<AutomationPlan> {
  const text = prompt.trim();
  const lower = text.toLowerCase();

  // Simulate latency so UIs can show an "agent thinking" state.
  await new Promise((r) => setTimeout(r, 400));

  const integrations: string[] = [];
  const tasks: string[] = [];

  if (lower.includes("linkedin")) integrations.push("linkedin");
  if (lower.includes("gmail") || lower.includes("email")) integrations.push("gmail");
  if (lower.includes("slack")) integrations.push("slack");
  if (lower.includes("notion")) integrations.push("notion");
  if (lower.includes("schedule") || lower.includes("daily") || lower.includes("weekly")) integrations.push("scheduler");

  // Always suggest AI generation for plans generated by this agent.
  integrations.push("ai_generation");

  // Common planning primitives
  if (lower.includes("research") || lower.includes("trend")) tasks.push("research trending topic");
  if (lower.includes("generate") || lower.includes("write") || lower.includes("create")) tasks.push("generate content");
  if (lower.includes("image") || lower.includes("photo") || lower.includes("graphic")) tasks.push("generate image");
  if (lower.includes("summarize") || lower.includes("summary")) tasks.push("summarize content");
  if (lower.includes("classify") || lower.includes("spam")) tasks.push("classify content");
  if (lower.includes("schedule") || lower.includes("calendar") || lower.includes("daily")) tasks.push("schedule action");
  if (lower.includes("publish") || lower.includes("post")) tasks.push("publish");
  if (lower.includes("send") || lower.includes("notify")) tasks.push("send notification");

  // Purpose-built examples
  if (lower.includes("linkedin") && (lower.includes("content") || lower.includes("post"))) {
    const plan: AutomationPlan = {
      workflow_name: "LinkedIn Content Automation",
      tasks: uniq([
        "research trending topic",
        "generate linkedin post",
        lower.includes("image") ? "generate image" : "",
        "schedule post",
        "publish linkedin",
      ].filter(Boolean)),
      suggested_integrations: uniq(["linkedin", "ai_generation", lower.includes("schedule") ? "scheduler" : "scheduler"]),
    };
    return plan;
  }

  const workflowName = (() => {
    if (lower.includes("linkedin")) return "LinkedIn Automation";
    if (lower.includes("gmail") || lower.includes("email")) return "Email Automation";
    if (lower.includes("slack")) return "Slack Automation";
    return "Automation Plan";
  })();

  const fallbackTasks = tasks.length
    ? tasks
    : ["identify trigger", "transform data with AI", "execute actions", "add error handling", "enable scheduling if needed"];

  return {
    workflow_name: workflowName,
    tasks: uniq(fallbackTasks),
    suggested_integrations: uniq(integrations),
  };
}

